### ISSUE TITLE
automatic commit: archive is too bit

### ISSUE THREAD

**Issue by hchasens** [teleshoes/music-db#1]
Bro... I want.... Your BOOKS!!!!!!!!!!

Like I need them. Unfortunately, we have a problem. GitHub saw your 1000 petaflops of data and was like "Nah brah" so now I cant access them. 

On a more serious note; If we could set up a pear to pear transfer, Dropbox, torrent (you would have to seed it), or something so I could "borrow" your books that would be great.

From your unknown but respected and noncreepy admirer of your book collection ~ yoyou446

hit me up at videogamesdev@gmail.com

**Comment by teleshoes** [comment]
haha, thanks! its only about 200GiB, btw.

unfortunately, while i disagree with US copyright law and the huge extent that it cripples creativity, restricts freedom, and puts the profit of the few before the rights of the many (not to mention how wildly ineffective it is at stopping people from pirating), i cannot share my audiobook collection as that is a federal crime with absolutely ridiculous penalties. fucken copyright law. (please dont ask again)

on a sidenote, this repo contains no copyrighted works, and never has. it is only the index of my music player's database (basically a song catalog), and is for consumption only by those developing my music player (of which i am currently the full development team).

its also a nice way to track what CDs ive bought recently, etc. but yea, its just text, no music or audio files.
