### ISSUE TITLE
Can you please share a file?

### ISSUE THREAD

**Issue by koshkamau** [teleshoes/music-db#2]
Sorry for this obviously illegitimate question, but I am interested in one particular file (directory actually) that is mentioned on your music-db.
As I understand it's a audiobook "Quarantine" by Greg Egan with 64kbps quality.
I found a torrent file for this book only on [one website](http://audiobookbay.nl/audio-books/quarantine-greg-egan/), but people there have only 97% of the book and there were no full seeds since summer.
Can you please share this book with me somehow ?

**Comment by teleshoes** [comment]
what a great book that is!
im very sorry, but despite the fact that i might disagree with the law, it is illegal for me to do so.

please consider buying a copy of this audiobook, as greg egan is a fantastic author (even if audiobook publishers are universally awful and put DRM in everything).

p.s.: this repo is actually just the cache for the music player app that i wrote (klomp), not an index for file sharing

**Comment by koshkamau** [comment]
Thank you for your response. 
Actually, the answer you gave was one of the most anticipated, considering circumstances...

Greg Egan is really outstanding author. I've read Quarantine and some other of his books (Dark Integers and Wang's Carpets left the most significant impression on me... ).

Buying a copy of a book is not an option for me. Price (about 20-25$) is too high. I do not consider myself as a poor man but the fact is that life which I live does not allow such expenses for impractical immaterial things. 
I'm not complaining!
I use audiobooks to improve my listening skills in English and there are plenty of other books and podcasts on the internet, including Egan's books. It just scratched in my mind that there is such a good but incomplete book on the tracker :)

I understand that your repo is not for file-sharing. I explored it for some time an saw a string somewhere "no copyrighted content here" or something like that. That is why I said that my question is illegitimate :)
I just should have asked.

**Comment by koshkamau** [comment]
Hi! It's me again :) I remember that you said that Quarantine is a great book, so I decided to recommend you a book. It's "Permafrost" by Alastair Reynolds. This book has completely different plot, but it leaves overall impression similar to Quarantine (plus a little bit of sadness).

**Comment by teleshoes** [comment]
thanks for the recommendation! ill definitely check it out. my friend is reading Revelation Space series right now and also recommended that, so i guess its time for me to start reading Alastair Reynolds ;)
